### ISSUE TITLE
Does not work with 'FOO-bar'

### ISSUE THREAD

**Issue by rottmann** [joakimbeng/kebab-case#6]
Result: '-f-o-o-bar'

**Comment by joakimbeng** [comment]
That's by design, see the leading section of the readme:

> this module doesn't modify the string in any other way than transforming uppercased letters to their lowercased counterparts prefixed with `-`. Thanks to this there's also a [reverse](https://github.com/joakimbeng/kebab-case#kebabcasereversestr) function to do the opposite, i.e. get back the original value.

If a string such as `FOO-bar` would be treated differently the `reverse` function wouldn't work as the api wouldn't be consistent regarding input vs output.

Maybe [dashify](https://www.npmjs.com/package/dashify) suits your need instead.
