### ISSUE TITLE
Options: to set not to use a leading -

### ISSUE THREAD

**Issue by demiro** [joakimbeng/kebab-case#7]
Currently a string like this KebabCase is translated to -kebab-case

an option to not use leading - and get: kebab-case, would be great

**Comment by lasagnamassage** [comment]
Hi! I submitted a PR for this exact functionality. Check it out https://github.com/joakimbeng/kebab-case/pull/12

**Comment by RoelRoel** [comment]
For this the library dashify exists.

**Comment by Nerdman4U** [comment]
Could we have this feature merged?
